---
Name: 'citanz-silverstripe-ecommerce'
---
# Member:
#   extensions:
#     - StoredCreditcardExtension
Cita\eCommerce\eCommerce:
  DefaultCurrency: 'NZD'
  AllowAnonymousCustomer: 1
  # CartlessProducts:
  #   - ClassName
Cita\eCommerce\Controller\eCommerceController:
  CompleteURL: "/cart/complete/"

SilverStripe\Security\Group:
  extensions:
    - Cita\eCommerce\Extension\MemberGroupExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Cita\eCommerce\Extension\SiteconfigExtension

Cita\eCommerce\Model\Order:
  default_buttons:
    complete_order:
      enabled: true
      label: 'Complete Order'
      extra_class: 'btn-primary'
      message: 'Order Complete!'
    cheque_cleared:
      enabled: true
      label: 'Cheque Cleared'
      extra_class: 'btn-primary'
      message: 'Cheque is cleared!'
    debit_cleared:
      enabled: true
      label: 'Debit Cleared'
      extra_class: 'btn-primary'
      message: 'Debit is cleared!'
    send_tracking:
      enabled: true
      label: 'Send Tracking Number'
      extra_class: 'btn-outline-primary'
      message: 'Tracking information has been sent!'
    send_invoice:
      enabled: true
      label: 'Resend Invoice'
      extra_class: ''
      message: 'Invoice has been sent!'
    refund:
      enabled: true
      label: 'Refund'
      extra_class: 'btn-outline-danger btn-hide-outline action-delete'
      message: 'Order has been refunded :('
    delete:
      enabled: false
      label: 'Delete'
      extra_class: 'btn-danger action-delete'
      message: 'Order has been deleted!'
    makeSnapshot:
      enabled: true
      label: 'Make Snapshot'
      message: 'Snapshot made'

Cita\eCommerce\Model\Freight:
  allowed_countries:
    Domestic:
      nz: New Zealand
    Zone A:
      au: Australia
    Zone B:
      ck: Cook Islands
      fj: Fiji
      nc: New Caledonia
      ws: Samoa
      to: Tonga
      vu: Vanuatu
    Zone C:
      kh: Cambodia
      ca: Canada
      cn: China
      in: India
      id: Indonesia
      jp: Japan
      kr: South Korea
      lk: Sri Lanka
      my: Malaysia
      ph: Philippines
      sg: Singapore
      th: Thailand
      us: United States
      vn: Vietnam
    Zone D:
      at: Austria
      be: Belgium
      hr: Croatia
      cz: Czech Republic
      dk: Denmark
      ec: Ecuador
      fi: Finland
      fr: France
      de: Germany
      gr: Greece
      hu: Hungary
      ie: Ireland
      it: Italy
      nl: Netherlands
      no: Norway
      pl: Poland
      pt: Portugal
      ro: Romania
      si: Slovenia
      es: Spain
      se: Sweden
      ch: Switzerland
      gb: United Kingdom
    Zone E:
      br: Brazil
      cl: Chile
      cr: Costa Rica
      sv: El Salvador
      mx: Mexico
      uy: Uruguay

SilverStripe\Omnipay\Model\Payment:
  extensions:
    - Cita\eCommerce\Extension\PaymentExtension

SilverStripe\Omnipay\Service\PurchaseService:
  extensions:
    - Cita\eCommerce\Extension\PurchaseServiceExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - resources/vendor/cita/ecommerce/client/css/cms.css
  extra_requirements_javascript:
    - resources/vendor/cita/ecommerce/client/js/cms.js
    - https://cdn.jsdelivr.net/npm/vue/dist/vue.js
    - https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js
    - resources/vendor/cita/ecommerce/client/js/vue.js
