---
Name: cita-ecommerce-routes
#After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'cita-ecommerce/poli-complete': 'Cita\eCommerce\Controller\PoliController'
    'cita-ecommerce/paystation-complete': 'Cita\eCommerce\Controller\PaystationController'
    'cita-ecommerce/dps-complete': 'Cita\eCommerce\Controller\DPSController'
    'cita-ecommerce/stripe-complete': 'Cita\eCommerce\Controller\StripeController'
    'cita-ecommerce/paypal-complete': 'Cita\eCommerce\Controller\PaypalController'
    'cita-ecommerce/complete/$ID!': 'Cita\eCommerce\Controller\eCommerceController'
    'cart//$action/$id': Cita\eCommerce\Controller\Cart
    'admin/cita-ecom/api/discount//$action': Cita\eCommerce\API\CMSDiscountAPI
